---
- name: "Install | Debian | Ensure PGDG repository GPG key is imported in apt keyring"
  become: true
  become_user: 'root'
  ansible.builtin.apt_key:
    url: "{{ debian.repo_gpg_url }}"
    keyring: "/etc/apt/trusted.gpg.d/pgdg.gpg"
    state: present

- name: "Install | Debian | Configure PGDG repository"
  become: true
  become_user: 'root'
  ansible.builtin.apt_repository:
    filename: "pgdg"
    repo: "{{ debian.repo_config }}"
    mode: "0644"
    update_cache: true
    state: present
