---
- name: "Configure | Debian | Deploy postgres configurations"
  loop:
    - { filename: 'postgresql.conf', owner: '{{ postgres.user }}', group: '{{ postgres.group }}', mode: '0644' }
    - { filename: 'pg_hba.conf',     owner: '{{ postgres.user }}', group: '{{ postgres.group }}', mode: '0640' } # yaml[commas]
  ansible.builtin.template:
    src: "postgresql/{{ item.filename }}.j2"
    dest: "{{ postgres.debian.conf_path }}/{{ postgres_version }}/main/{{ item.filename }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: true
