---
- name: 'Import preconfigure tasks'
  ansible.builtin.import_tasks: prerequisites/main.yml
  tags:
    - always

- name: 'Import install tasks'
  ansible.builtin.import_tasks: install/main.yml

- name: 'Import configure tasks'
  ansible.builtin.import_tasks: configure/main.yml

- name: 'Import backup tasks'
  ansible.builtin.import_tasks: backup/main.yml
  tags:
    - backup
