---
- name: 'Backup | Ensure target folders exists'
  loop: "{{ folders | dict2items }}"
  tags:
    - backup
    - postgres_backup
  vars:
    folders:
      base:
        path: "{{ pg_bkp_base_path }}"
        owner: 'root'
        group: 'root'
        mode: '0751'
      dump:
        path: "{{ pg_bkp_dump_target_dir }}"
        owner: "{{ postgres.user }}"
        group: "{{ postgres.group }}"
        mode: '0700'
      conf:
        path: "{{ pg_bkp_conf_target_dir }}"
        owner: "{{ postgres.user }}"
        group: "{{ postgres.group }}"
        mode: '0700'
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
    state: directory

- name: 'Backup | Perform backup'
  become: true
  become_user: '{{ postgres.user }}'
  tags:
    - backup
    - postgres_backup
  block:
    - name: 'Backup | List databases'
      register: postgresql_dblist
      community.postgresql.postgresql_info:
        filter:
          - databases

    - name: 'Backup | Dump databases'
      become: true
      become_user: '{{ postgres.user }}'
      loop: "{{ postgresql_dblist['databases'] | flatten(levels=1) }}"
      when:
        - item != 'template0'
        - item != 'template1'
      community.postgresql.postgresql_db:
        name: "{{ item }}"
        state: dump
        target: "{{ pg_bkp_dump_target_dir }}/{{ item }}.{{ ansible_date_time['weekday'] }}.sql"

    - name: 'Backup | list uncompressed dump files'
      register: postgresql_dumplist
      ansible.builtin.find:
        paths: '{{ pg_bkp_dump_target_dir }}'
        patterns: '*.sql'

    - name: "Backup | Compress database dumps"
      loop:
        - '{{ postgresql_dumplist.files }}'
      community.general.archive:
        path: '{{ item.path }}'
        format: gz
        remove: true
        owner: '{{ postgres.user }}'
        group: '{{ postgres.group }}'
        mode: '0600'
